### PR TITLE
Add missing dependency: chai

### PR DESCRIPTION
**Pull request by hootlex**

### CODE REVIEW

**Comment by chrisvfritz** [comment]
Chai isn't used in this project, so it's not really missing. Did you encounter an error that pointed to chai?

**Comment by hootlex** [comment]
Yeah. When I ran `npm run test -s` I got this error:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Code/clones/vue-migration-helper/node_modules/ajv-keywords/spec/define_keywords.spec.js:5:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Installing `chai` solved it.

**Comment by chrisvfritz** [comment]
Ah, I see. Jasmine was trying to run the test of an installed dependency in `node_modules` and that test required `chai`. I'm not sure why it's not ignoring `node_modules` for you, but I just [updated the file patterns](https://github.com/vuejs/vue-migration-helper/commit/6ecf9f4b0d95a378497849d2244d95275f1a5db8) to match, so that only the source directories are explicitly searched for `.spec.js` files.

Let me know if that resolves the problem for you.

**Comment by hootlex** [comment]
Yup, it works fine now. :)

BTW, are tests within `spec/e2e/basic.spec.js` supposed to pass? They are failing.

This is the error output:
```
Failures:
1) scanning empty directory completes without error
  Message:
: No such file or directory node
    ' to be ''.
  Stack:
: No such file or directoryin/env: node
    ' to be ''.
        at Object.it (/home/vagrant/Code/clones/vue-migration-helper/spec/e2e/basic.spec.js:5:27)

2) scanning directory with an empty file completes without error
  Message:
: No such file or directory node
    ' to be ''.
  Stack:
: No such file or directoryin/env: node
    ' to be ''.
        at Object.it (/home/vagrant/Code/clones/vue-migration-helper/spec/e2e/basic.spec.js:14:27)

3) scanning directory with a simple js file completes without error
  Message:
: No such file or directory node
    ' to be ''.
  Stack:
: No such file or directoryin/env: node
    ' to be ''.
        at Object.it (/home/vagrant/Code/clones/vue-migration-helper/spec/e2e/basic.spec.js:23:27)
```

**Comment by hootlex** [comment]
@chrisvfritz Hmm, that's weird. All the other tests are ok.

**Comment by chrisvfritz** [comment]
Yeah, only the e2e tests run the binary, which [relies on `node` being in the path](https://github.com/vuejs/vue-migration-helper/blob/master/index.js#L1).

**Comment by hootlex** [comment]
Got it working by changing `results` within `run-migration-helper` to:

```javascript
  const results = spawnSync(
    "node", [path.join(__dirname, '../../index.js'), ...folders.map(folder => 'spec/fixtures/projects/' + folder)], {
      cwd: path.join(__dirname, '../..')
    }
  )
```

**Pull request closed without merging**
