### PR TITLE
Track statiscticts for project's files

### PR DESCRIPTION
**Pull request by hootlex**
I think it'd be nice to track the checked files and display the stats when all checks are complete.

This is useful to track the progress of the migration and get happy when all project files don't use deprecated patterns.

Output when there are errors:

Output where all files are ok:

### CODE REVIEW

**Comment by hootlex** [comment]
@chrisvfritz what are your thoughts on this?

**Comment by chrisvfritz** [comment]
Yeah, I think a summary at the end could be nice. Will add this soon. 🙂

**Comment by hootlex** [comment]
It is almost ready. The only missing thing is the tests. :)

**Comment by chrisvfritz** [comment]
Great! Let me know when it's ready for review.

**Comment by hootlex** [comment]
It is ready for review.

**Comment by chrisvfritz** [comment]
Sorry, but thinking about this a bit more, I decided to print more information if no deprecations are found, but nothing otherwise. I'd like to place less emphasis on the total number of deprecations found, as some warnings rely on others being fixed first and we only report a single warning per line (so that users can upgrade more gradually). I gave you a shoutout in the commit though!

**Comment by hootlex** [comment]
No problem.  Next time you can point me to the right direction to do it together. :)

I am thinking about a `generate` or `overwrite` command which will apply some of the suggested fixes on the files. I am not saying all fixes because only some patterns can be automatically replaced.
How does this sound?

**Comment by chrisvfritz** [comment]
I think if we eventually add rules that use ESLint or Vue's own parser, that would be a great feature. Right now though, all matching is just done in regex and while that allows us to write rules faster, I don't feel confident enough that there'll be no false positives or replacement mistakes to edit code on a user's behalf - especially since we can't guarantee that they're using version control or backups.

**Comment by hootlex** [comment]
I understand. Maybe we could create a new file (`filename-vue2.fileextension`) and put the migrated code there instead of overwriting.
I think that this feature will be very useful to some developers, especially the ones with small projects.

**Comment by chrisvfritz** [comment]
I think it would be a considerable amount of work and provide too little gain, since users would still have to review the generated files to ensure no mistakes were made, then delete the old files and rename the new ones. For now, I'd like to focus on just getting rules for vue-router and vuex finished.

**Pull request closed without merging**
